# Generated by Django 5.2.17 on 2026-09-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numb_of_reviews',
            field=models.IntegerField(),
        ),
    ]
