# Generated by Django 5.2.17 on 2026-09-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_product_numb_of_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numb_of_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
