# Generated by Django 5.2.17 on 2026-09-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_alter_product_numb_of_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numb_of_reviews',
            field=models.CharField(default=0),
        ),
    ]
