# Generated by Django 5.2.17 on 2026-09-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_alter_product_numb_of_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numb_of_reviews',
            field=models.CharField(blank=True, null=True),
        ),
    ]
